version: 1.0.{build}

os: WMF 5

# Skip on updates to the readme
skip_commits:
  message: /readme*/
  
install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module -Name Pester -Force
  - ps: Install-Module PsScriptAnalyzer -Force
  
build: false

test_script:
  - ps: |
      $PesterResults = Invoke-Pester -Path ".\Tests" -OutputFile TestsResults.xml -OutputFormat NUnitXml -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
      $FailedCount = $PesterResults.FailedCount
      If ($FailedCount -gt 0) {
        Add-AppveyorMessage -Message "$($FailedCount) Pester tests failed."

        # Failing the build
        Throw "Build failed because $($FailedCount) Pester tests failed."
      }
