version: 1.0.{build}

os: WMF 5

# Skip on updates to the readme
skip_commits:
  message: /readme*/
  
install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module -Name Pester -Force
  - ps: Install-Module PsScriptAnalyzer -Force
  
build: false

test_script:
  - ps: |
      Add-AppveyorTest -Name "Pester" -Outcome Running
      Write-Host "Just before invoking Pester"
      $PesterResults = Invoke-Pester -Path ".\Tests" -PassThru
      $FailedCount = $PesterResults.FailedCount
      If ($FailedCount -gt 0) {
        Add-AppveyorMessage -Message "$FailedCount.ToString() Pester tests failed.`
        Check the console ouput for details." -Category Error
        Update-AppveyorTest -Name "Pester" -Outcome Failed -ErrorMessage "$FailedCount.ToString() Pester tests failed."

        # Failing the build
        Throw "Build failed because the Pester tests failed"
      }
      Else {
        Write-Host "Entering the case when the Pester test passed"
        Update-AppveyorTest -Name "Pester" -Outcome Passed
      }
      Write-Host "Finished Pester tests"
  - ps: |
      Add-AppveyorTest -Name "PsScriptAnalyzer" -Outcome Running
      Write-Host "Just before invoking PSScriptAnalyzer"
      $PSSAResults = Invoke-ScriptAnalyzer -Path $pwd -Recurse -Severity Error -ErrorAction SilentlyContinue
      If ($PSSAResults) {
        write-host "Entering the block when PsScriptAnalyzer has results"
        $PSSAResultString = $PSSAResults | Out-String
        Write-Warning $PSSAResultString
        Add-AppveyorMessage -Message "PSScriptAnalyzer output contained one or more result(s) with 'Error' severity.`
        Check the 'Tests' tab of this build for more details." -Category Error
        Update-AppveyorTest -Name "PsScriptAnalyzer" -Outcome Failed -ErrorMessage $PSSAResultString
        
        # Failing the build
        Throw "Build failed because the PsScriptAnalyzer tests failed"
      }
      Else {
        Update-AppveyorTest -Name "PsScriptAnalyzer" -Outcome Passed
      }